# Generated by Django 4.2.13 on 2026-03-30 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('model_type', models.CharField(default='matrix_factorization', max_length=50)),
                ('n_factors', models.IntegerField(default=10)),
                ('n_epochs', models.IntegerField(default=100)),
                ('learning_rate', models.FloatField(default=0.01)),
                ('regularization', models.FloatField(default=0.01)),
                ('is_active', models.BooleanField(default=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
                ('last_retrained', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Recommendation Model',
                'verbose_name_plural': 'Recommendation Models',
            },
        ),
        migrations.CreateModel(
            name='UserSimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField(help_text='Cosine similarity score (0-1)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarities_from', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarities_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Similarity',
                'verbose_name_plural': 'User Similarities',
                'unique_together': {('user1', 'user2')},
            },
        ),
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0, help_text='0-5 stars')),
                ('interaction_type', models.CharField(choices=[('view', 'View'), ('wishlist', 'Wishlist'), ('purchase', 'Purchase'), ('review', 'Review')], max_length=20)),
                ('interaction_weight', models.FloatField(default=1.0, help_text='Weight for collaborative filtering')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ratings', to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Rating',
                'verbose_name_plural': 'User Ratings',
                'indexes': [models.Index(fields=['user', 'book'], name='recommendat_user_id_f8ad52_idx'), models.Index(fields=['created_at'], name='recommendat_created_cf0a5e_idx')],
                'unique_together': {('user', 'book', 'interaction_type')},
            },
        ),
        migrations.CreateModel(
            name='RecommendedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_score', models.FloatField(help_text='Predicted rating 0-5')),
                ('recommendation_type', models.CharField(default='collaborative_filtering', max_length=50)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('is_clicked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recommended Book',
                'verbose_name_plural': 'Recommended Books',
                'ordering': ['-recommendation_score'],
                'unique_together': {('user', 'book')},
            },
        ),
    ]
